name: Check
on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v4
      with:
        path: |
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/checkout@v4

    - run: cargo clippy --all -- -D warnings
